version: 2
updates:
  # ===================================================================
  # NPM: Produktions-Abhängigkeiten (Sicherheitsfokus)
  # ===================================================================
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5 # Reduziert, da Dev-Deps separat laufen
    reviewers:
      - "Kryptonator"
    assignees:
      - "Kryptonator"
    commit-message:
      prefix: "📦"
      include: "scope"
    labels:
      - "dependencies"
      - "production"
      - "security-review"
    # Schließe Entwicklungs-Abhängigkeiten aus, diese werden separat behandelt
    exclude-patterns:
      - "*-loader"
      - "eslint*"
      - "*-plugin"
      - "test-*"
      - "prettier*"
      - "webpack*"
      - "babel*"
      - "jest*"
      - "postcss*"
      - "@playwright*"
      - "selenium*"
      - "cssnano" # Gehört eher zu Dev/Build
    # Gruppiere verwandte Pakete
    groups:
      tailwind-ecosystem:
        patterns:
          - "tailwindcss"
          - "autoprefixer"
    # Automatisches Mergen nur für Patches, um Stabilität zu gewährleisten
    automerge: true
    automergeable-types:
      - "security:patch"
      - "version-update:semver-patch"
    rebase-strategy: "auto"

  # ===================================================================
  # NPM: Entwicklungs-Abhängigkeiten (Automatisierungsfokus)
  # ===================================================================
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday" # An einem anderen Tag, um Konflikte zu vermeiden
      time: "10:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "Kryptonator"
    assignees:
      - "Kryptonator"
    commit-message:
      prefix: "🔧"
      include: "scope"
    labels:
      - "dependencies"
      - "dev-dependencies"
    # Schließe nur Entwicklungs-Abhängigkeiten ein
    include-patterns:
      - "*-loader"
      - "eslint*"
      - "*-plugin"
      - "test-*"
      - "prettier*"
      - "webpack*"
      - "babel*"
      - "jest*"
      - "postcss*"
      - "@playwright*"
      - "selenium*"
      - "cssnano"
    # Aggressiveres Auto-Merging für Dev-Tools, inkl. Minor-Updates
    automerge: true
    automergeable-types:
      - "security:patch"
      - "version-update:semver-patch"
      - "version-update:semver-minor"
    rebase-strategy: "auto"

  # ===================================================================
  # GitHub Actions (CI/CD)
  # ===================================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    reviewers:
      - "Kryptonator"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    commit-message:
      prefix: "👷"
      include: "scope"
    automerge: true
    automergeable-types:
      - "security:patch"
      - "version-update:semver-patch"

  # ===================================================================
  # Docker-Container
  # ===================================================================
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "🐳"
      include: "scope"

# Globale Einstellungen für alle Ecosystems
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GITHUB_TOKEN}}
    
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    
# Spezielle Erlaubte Lizenzen (Compliance-Filter)
allowed-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - 0BSD
  - CC0-1.0
  - Unlicense
