# 🚀 NETLIFY BACKUP DEPLOYMENT

## SOFORT-ALTERNATIVE zu GitHub Pages

### **netlify.toml - Deployment-Konfiguration:**
```toml
[build]
  publish = "."
  command = "echo 'Static site deployment'"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
```

### **SOFORT-DEPLOYMENT SCHRITTE:**

1. **Netlify Account** erstellen/einloggen
2. **GitHub Repository** verbinden: `Kryptonator/burnitoken`
3. **Build Settings:**
   - Build command: (leer lassen)
   - Publish directory: `/`
   - Branch: `master`
4. **Custom Domain** hinzufügen: `burnitoken.website`
5. **SSL** aktivieren (automatisch)

### **DOMAIN SETTINGS:**
```
Primary domain: burnitoken.website
DNS Management: Netlify DNS oder externe DNS
SSL Certificate: Let's Encrypt (automatisch)
```

### **BACKUP-URLS (sofort verfügbar):**
- `https://burnitoken.netlify.app` (automatisch)
- `https://burnitoken.website` (nach DNS-Setup)

### **VORTEILE:**
- ✅ Sofortige Deployment-Pipeline
- ✅ Automatische SSL-Zertifikate
- ✅ CDN inklusive
- ✅ 99.9% Uptime SLA
- ✅ Instant Rollbacks
