// alert-service.js
// Zentrale Alert-Funktion für kritische Fehler/Status (Slack, Webhook, E-Mail)
// Nutzung: require('./tools/alert-service').sendAlert(...)

const https = require('https');
const url = require('url');
const nodemailer = require('nodemailer');
const { createGitHubIssue } = require('./github-issue-creator'); // Importiert den Issue Creator

// E-Mail-Konfiguration (aus Umgebungsvariablen laden!)
const mailConfig = {
  host: process.env.EMAIL_HOST,
  port: process.env.EMAIL_PORT || 587,
  secure: process.env.EMAIL_PORT == 465, // true for 465, false for other ports
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
};

const transporter = nodemailer.createTransport(mailConfig);

/**
 * Sende einen Alert an einen Webhook und/oder per E-Mail.
 * @param {Object} options
 * @param {string} options.message - Die Nachricht (Pflichtfeld)
 * @param {string} [options.webhookUrl] - Die Webhook-URL (optional)
 * @param {string} [options.level] - z.B. 'error', 'warning', 'info'
 * @param {Object} [options.extra] - Zusätzliche Daten (optional)
 * @param {boolean} [options.sendEmail] - Ob eine E-Mail gesendet werden soll (optional)
 * @param {boolean} [options.createIssue] - Ob ein GitHub Issue erstellt werden soll (Standard: true für Fehler)
 */
function sendAlert({ message, webhookUrl, level = 'error', extra = {}, sendEmail = false, createIssue = (level === 'error') }) {
  if (!message) return;

  const subject = `[${level.toUpperCase()}] Wichtige Meldung für BurniToken`;
  const text = `Hallo,\n\nes gibt eine neue Meldung für das Projekt BurniToken:\n\n${message}\n\nDetails:\n${JSON.stringify(extra, null, 2)}\n\nViele Grüße,\nDein automatisierter Überwachungs-Dienst`;

  const payload = {
    text: `[${level.toUpperCase()}] ${message}`,
    ...extra
  };

  // Webhook senden
  if (webhookUrl) {
    const parsedUrl = url.parse(webhookUrl);
    const data = JSON.stringify(payload);
    const req = https.request({
      hostname: parsedUrl.hostname,
      path: parsedUrl.path,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': data.length
      }
    }, res => {});
    req.on('error', (e) => {
      console.error('Alert-Webhook-Fehler:', e);
    });
    req.write(data);
    req.end();
  }

  // E-Mail senden
  if (sendEmail && mailConfig.host && mailConfig.auth.user) {
    transporter.sendMail({
      from: '"BurniToken CI" <' + mailConfig.auth.user + '>',
      to: 'burn.coin@yahoo.com',
      subject: subject,
      text: text,
    }, (error, info) => {
      if (error) {
        return console.error('E-Mail-Fehler:', error);
      }
      console.log('E-Mail gesendet:', info.messageId);
    });
  }

  // GitHub Issue erstellen (nur bei Fehlern und wenn aktiviert)
  if (createIssue) {
    try {
      const issueTitle = message;
      const issueBody = `**Fehlerdetails:**\n\n\`\`\`json\n${JSON.stringify(extra, null, 2)}\n\`\`\`\n\n**Kontext:**\n\nDieser Fehler wurde vom automatisierten System-Monitoring erkannt. Bitte untersuchen Sie die Ursache und beheben Sie das Problem.`;
      
      // Labels je nach Dringlichkeit anpassen
      const labels = ['bug', 'autogenerated', 'critical-alert'];

      createGitHubIssue(issueTitle, issueBody, labels)
        .then(issueUrl => console.log(`🔗 GitHub Issue wurde erstellt: ${issueUrl}`))
        .catch(err => console.error(`Fehler beim Erstellen des GitHub Issues aus dem Alert-Service: ${err.message}`));

    } catch (err) {
      console.error(`Konnte GitHub Issue nicht erstellen: ${err.message}`);
    }
  }

  if (!webhookUrl && !sendEmail && !createIssue) {
    // Fallback: Logge Alert lokal, wenn keine Benachrichtigungsmethode konfiguriert ist
    console.error('ALERT:', payload);
  }
}

module.exports = { sendAlert };
