# Netlify Plugin-Konfiguration für Lighthouse und andere Plugins

# Lighthouse-Plugin-Konfiguration
[plugins.inputs]
  # URLs, die geprüft werden sollen
  urls = [
    "https://burnitoken.website/",
    "https://burnitoken.website/about",
    "https://burnitoken.website/contact"
  ]
  # Einstellungen für Desktop-Prüfungen
  [[plugins.inputs.audits]]
    [plugins.inputs.audits.desktop]
      performance = 90
      accessibility = 90
      best-practices = 90
      seo = 90
      pwa = 50
  
  # Einstellungen für Mobile-Prüfungen
  [[plugins.inputs.audits]]
    [plugins.inputs.audits.mobile]
      performance = 80
      accessibility = 90
      best-practices = 85
      seo = 90
      pwa = 50
  
  # Berichte konfigurieren
  [plugins.inputs.settings]
    output = "reports/lighthouse"
    locale = "de"
    throttling = "mobileSlow4G"
    onlyCategories = ["performance", "accessibility", "best-practices", "seo"]
    skipAudits = ["uses-http2"]
