# .github/workflows/license-check.yml
name: '📜 License Check'

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  dependency-review:
    name: 'Check for license compatibility'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          # Erlaubte Lizenzen (SPDX-Identifier)
          allow-licenses: >
            MIT,
            Apache-2.0,
            BSD-2-Clause,
            BSD-3-Clause,
            ISC,
            0BSD,
            CC0-1.0,
            Unlicense

          # Strenge Prüfung: Fehler bei Paketen ohne deklarierte Lizenz
          fail-on-unlicensed: true

          # Strenge Prüfung: Fehler bei Paketen mit nicht erlaubten Lizenzen
          fail-on-violations: true
