name: Disaster Recovery Test

on:
  schedule:
    - cron: '0 3 * * 0' # Jeden Sonntag um 03:00 UTC
  workflow_dispatch:

jobs:
  disaster-recovery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Finde letzten erfolgreichen Deploy-Tag
        id: last_tag
        run: |
          TAG=$(git tag --list 'deploy-*' --sort=-creatordate | head -n 1)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Teste Rollback auf letzten Deploy-Tag
        run: |
          TAG="${{ steps.last_tag.outputs.tag }}"
          if [ -z "$TAG" ]; then
            echo "Kein Deploy-Tag gefunden. Test abgebrochen."; exit 1;
          fi
          git reset --hard $TAG
          echo "Rollback auf $TAG simuliert."
      - name: Health-Check nach Rollback
        run: |
          # Beispiel: Prüfe README und wichtige Reports
          for file in README.md SEO_STATUS.md STATUS.md; do
            if [ ! -f "$file" ]; then
              echo "Fehler: $file fehlt nach Rollback!"; exit 1;
            fi
          done
          echo "Alle Kern-Dateien nach Rollback vorhanden."
      - name: Dokumentiere Recovery-Test als Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Disaster Recovery Test Report: ${{ steps.last_tag.outputs.tag }}"
          content-filepath: STATUS.md
          labels: recovery, automated, test
