name: Playwright E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start local server
        run: |
          npx http-server -p 8080 &
          sleep 5
      - name: Run Playwright E2E Tests
        run: npx playwright test tests/e2e/userflow.spec.js
      - name: Run Playwright Visual Regression
        run: npx playwright test tests/e2e/visual.spec.js
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
