name: QA Reports & Alerts

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 8 * * *' # Täglich um 8 Uhr UTC

jobs:
  run-qa-suite:
    name: 🧪 Run Full QA Suite
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🏗️ Build project
        run: npm run build

      - name: 🚀 Start server in background
        run: npm run serve &

      - name: ⏱️ Wait for server to be ready
        run: npx wait-on http://localhost:8080 -t 60000

      - name: 🛡️ Run QA, Tests & Reports
        run: |
          set -eo pipefail
          npm run lint:report
          npm run validate || true
          npm run test:e2e:ci || true
          npm run lighthouse || true

      - name: 📝 Generate Status Page
        if: always()
        run: node tools/generate-status-page.js
        
      - name: 📤 Archive Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-reports
          path: |
            status.html
            playwright-report/
            .lighthouseci/
            .html-validate-report/
            lint-results.json

      - name: 📧 Send mail on failure
        if: failure()
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
        run: |
          node -e 'require("./tools/alert-service").sendAlert({ 
            message: "QA Workflow Failed in ${{ github.repository }}", 
            level: "critical", 
            extra: { 
              repository: "${{ github.repository }}", 
              commit: "${{ github.sha }}", 
              workflow: "${{ github.workflow }}" 
            }, 
            email: { 
              to: process.env.ALERT_EMAIL, 
              subject: "❌ QA Workflow Failed: ${{ github.repository }}" 
            } 
          })'
