name: QA Reports & Alerts

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 6 * * *' # Täglich um 6 Uhr UTC

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Start webserver
        run: npm run serve &
      - name: Wait for server
        run: npx wait-on http://localhost:8080
      - name: Run Playwright E2E tests
        run: npm run test:e2e -- --reporter=html
      - name: Run Lighthouse CI
        run: npm run lighthouse
      - name: Run HTML validation
        run: npm run validate
      - name: Run Prettier check
        run: npm run lint:check
      - name: Archive Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
      - name: Archive Lighthouse reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: .lighthouseci/
      - name: Archive HTML validation results
        uses: actions/upload-artifact@v4
        with:
          name: html-validation
          path: .html-validate-report/
      - name: Send mail on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "❌ QA/Deploy Fehler: ${{ github.repository }} @ ${{ github.sha }}"
          to: ${{ secrets.ALERT_EMAIL }}
          from: QA-Bot <${{ secrets.ALERT_EMAIL }}>
          body: |
            Fehler im QA-/Deploy-Workflow!
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Siehe GitHub Actions für Details.
